export default {
  type: undefined,
  distance: 'Anywhere',
  zip: undefined,
  countryCode: undefined,
  name: undefined,
  age: [],
  size: [],
  gender: [],
  breed: [],
  goodWith: [],
  care: [],
  coatLength: [],
  color: [],
  days: [],
};
