export const SEARCH_PET_REQUEST = 'SEARCH_PET_REQUEST';
export const SEARCH_PET_FAILURE = 'SEARCH_PET_FAILURE';
export const SEARCH_PET_SUCCESS = 'SEARCH_PET_SUCCESS';

export const CLEAR_PETS_SEARCH = 'CLEAR_PETS_SEARCH';
