export const SEARCH_PET_REQUEST = 'SEARCH_PET_REQUEST';
export const SEARCH_PET_FAILURE = 'SEARCH_PET_FAILURE';
export const SEARCH_PET_SUCCESS = 'SEARCH_PET_SUCCESS';

export const CLEAR_PETS_SEARCH = 'CLEAR_PETS_SEARCH';

export const FETCH_LATEST_ANIMALS_REQUEST = 'FETCH_LATEST_ANIMALS_REQUEST';
export const FETCH_LATEST_ANIMALS_SUCCESS = 'FETCH_LATEST_ANIMALS_SUCCESS';
export const FETCH_LATEST_ANIMALS_FAILURE = 'FETCH_LATEST_ANIMALS_FAILURE';
