export const initialFormState = {
  fields: {
    name: { value: undefined },
    type: { value: undefined },
    species: { value: undefined },
    gender: { value: undefined },
    age: { value: undefined },
    attributes: { value: [] },
    environment: { value: [] },
    primaryBreed: { value: undefined },
    secondaryBreed: { value: undefined },
    mixedBreed: { value: [] },
    unknownBreed: { value: [] },
    coatLength: { value: undefined },
    size: { value: undefined },
    colors: { value: [] },
    microchip: { value: [] },
    chipId: { value: undefined },
    chipBrand: { value: undefined },
    chipLocation: { value: undefined },
    chipDescription: { value: undefined },
    description: { value: undefined },
    tags: { value: [] },
    phone: { value: undefined },
    email: { value: undefined },
    country: { value: undefined },
    city: { value: undefined },
    address: { value: undefined },
    profileImage: { value: [] },
    galleryImages: { value: [] },
  },
};
