export const CREATE_PET_REQUEST = 'CREATE_PET_REQUEST';
export const CREATE_PET_SUCCESS = 'CREATE_PET_SUCCESS';
export const CREATE_PET_FAILURE = 'CREATE_PET_FAILURE';

export const GET_ADDED_PETS = 'GET_ADDED_PETS';
export const GET_ADDED_PETS_SUCCESS = 'GET_ADDED_PETS_SUCCESS';
export const GET_ADDED_PETS_FAILURE = 'GET_ADDED_PETS_FAILURE';
