export const TOGGLE_SEARCH_FILTER = 'TOGGLE_SEARCH_FILTER';
export const PERSIST_SEARCH_FORM = 'PERSIST_SEARCH_FORM';
export const PERSIST_QUERY_STRING = 'PERSIST_QUERY_STRING';
export const CLEAR_SEARCH_FORM = 'CLEAR_SEARCH_FORM';
